### ISSUE TITLE
Lack of support for non-latin characters

### ISSUE THREAD

**Issue by PhotoPaul** [LiveChurchSolutions/ChumsTransfer#5]
Importing files with non-latin characters results to the following:

![image](https://user-images.githubusercontent.com/3471804/164039219-768345ae-78d3-4837-9029-7050bae93e53.png)

**Comment by jzongker** [comment]
This turned out to be a database configuration issue rather than an app issue.  Updated the live and staging databases to use the utf8mb4 charset instead of latin1.

[utf8.zip](https://github.com/LiveChurchSolutions/ChumsTransfer/files/8525231/utf8.zip)

**Comment by PhotoPaul** [comment]
@jzongker I added the same change to utf8mb4 on Dev as well (it was only on Prod). Now a user can register using non-latin characters for their name.
