### ISSUE TITLE
Profile picture urls are wrong after import [Low Priority]

### ISSUE THREAD

**Issue by PhotoPaul** [LiveChurchSolutions/ChumsTransfer#6]
Default profile picture doesn't show for users after importing, because when the field `membership.people.photoUpdated` is `null`, it gets set to the time of the import instead of staying as `null`.

![image](https://user-images.githubusercontent.com/3471804/169661882-930401a3-29d6-4d47-9ef4-62deaa319bb7.png)

**Comment by jzongker** [comment]
Just a note that we do import the photo too if one is provided, so when fixing this be sure the date still gets set if there is indeed a photo imported.
